version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: "python3 main.py"
    ports:
     - "5001:5001"
    volumes:
      - /uploads:/file_docker/uploads
      - /downloads:/file_docker/downloads
    depends_on:
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A main.celery worker --loglevel=info"
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    volumes:
      - /uploads:/file_docker/uploads
      - /downloads:/file_docker/downloads
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  redis: {}